ifeq ($(CONFIG_ONEPLUS_CHARGER_MTK6763)_$(CONFIG_ONEPLUS_CHARGER_MTK6771),n_n)
obj-y	+= oneplus_pic16f.o
endif

obj-y	+= oneplus_n76e.o
obj-y	+= oneplus_warp_fw.o
obj-y	+= oneplus_stm8s.o
obj-y	+= oneplus_rk826.o
obj-y	+= oneplus_op10.o
