
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/qcom/
subdir-ccflags-y += -DOPLUS_FEATURE_CHG_BASIC
subdir-ccflags-y += -DCONFIG_OPLUS_CHARGER

obj-y      += charger_ic/
obj-y      += warp_ic/
obj-y      += gauge_ic/

obj-y	+= oplus_charger.o
obj-y	+= oplus_gauge.o
obj-y	+= oplus_warp.o
obj-y	+= oplus_adapter.o
obj-y	+= oplus_wireless.o
obj-y	+= oplus_short.o
