#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-y  += ili9882n_qcom.o \
               ili9882n_ic.o \
               ili9882n_mp.o \
               ili9882n_fw.o \
               ili9882n_node.o
#endif
