#fingerprint_detect should before fpc1022
obj-$(CONFIG_FINGERPRINT_DETECT)    += fingerprint_detect/
obj-$(CONFIG_FINGERPRINT_GOODIX)    += goodix/
obj-$(CONFIG_FINGERPRINT_EGIS520)   += egis520/
obj-$(CONFIG_FINGERPRINT_ET520)     += et520/
