#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_ILITEK_ILITEK9881H_V3) += ilitek9881h_v3/
#endif
obj-$(CONFIG_TOUCHPANEL_ILITEK_ILITEK9881H_V3) += ilitek9882n/
